#!/bin/bash

dom=$(date +%-d)
dow=$((dom % 7))
week=$(date +%V)
year=$(date +%Y)

if [ "$dow" -lt 5 ]
then
  week=$(expr $week - 2)
else
  week=$(expr $week - 1)
fi

open http://coub.com/weekly/$year/$week
